# Generated by Django 3.2.8 on 2021-10-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sensor', models.CharField(max_length=255)),
                ('val', models.FloatField()),
            ],
            options={
                'unique_together': {('time', 'sensor')},
            },
        ),
        migrations.CreateModel(
            name='ModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('observe_window', models.IntegerField()),
                ('predict_gap', models.IntegerField()),
                ('predict_len', models.IntegerField()),
                ('para_d', models.IntegerField()),
                ('para_r', models.IntegerField()),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('model_name', 'observe_window', 'predict_gap', 'predict_len', 'para_d', 'para_r')},
            },
        ),
    ]
